
version: '3'
services:
  site:
    container_name: NaturalFarming
    command: jekyll serve --watch --drafts
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
